language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
  nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
    app: qc-engine
  on:
    repo: Quick-Command/qc-engine
  run: rails db:migrate
