language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- gem install bundler:2.1.4
- nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: LZxe7W9BC6kPhvpF/etzLhxF8YzUaJAVQ4Z8WrLFzBFC1tBIKayeyEyJpOJi0Irp52sHirkNE22opFixl6IBECMaJi84ua/3rSeQ/EJ7++CJRjzfYgLXiEgzu7eNkuxOAScuvtl7I5gT/lnwtPSZuSIl9R/YphrnpuTPc2F+uthuEziKdCMWOrYo3ztzwx0OPTaHpsoKmbthWsrkbXfn4uu4qYm+6PXraCRDuSuMl85yaTtRt1wZRlp4yAeFYIn5pmhCLuRWtuVg4T1P+K1khrhUmPMOINNjfOHLAwXz5RS/Ky4BDAd2eYJjq/RX7LQE51bcJ0akMGVNE5zsx1vWQhWc0jk/77yIE8zbrjkCv7OHkG8q5t9GHE9mDFK5mr1WjnBs/cNIA90SExrScF96wpJ8wEf7Ryni9MoKrIH0iuxRImiAv0/wta8FfgEXGBjXGiSEB/AOzdlSaANgXDLggQvQeGvjcm742VEz9AeSfARmoE7rsKzosESFeYatKG75oKq9HK/RACQIWiNsnwVMjLV7O+h06SMUx9zHSCKfhmGQiwkP9P+m7aanFWxcG2NZoJVDS+80muYEqcNzTXpI7+jLKHu1jRFE+UA+CH3iuocCqxwcYDS/GdPY7roQM3+RZ7b020QpFKkDKpeldF3+pTdbHOCp0H7LukCm+7mPXlM=
  app: qc-engine
  on:
    repo: Quick-Command/qc-engine
    run: rails db:migrate
